server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # SPA yönlendirmesi: Bulunamayan tüm yolları index.html'e yönlendirir
        try_files $uri $uri/ /index.html;

        # Content Security Policy (Allows 'unsafe-eval' and 'unsafe-inline' for Expo/React Native Web)
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: http:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https: wss:; manifest-src 'self'; worker-src 'self';" always;

        # Diğer Güvenlik Başlıkları
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
    }

    # Hata sayfaları
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
